# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
            exclude: ^(deps/|src/jl/|inst/|R/|man/|dash_query_builder/_imports_.py|dash_query_builder/.+\.(js))
          - id: check-yaml
          - id: check-added-large-files
            args: [--maxkb=1500]
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.1.0 # Use the sha or tag you want to point at
      hooks:
          - id: prettier
            exclude: ^(deps/|src/jl/|inst/|R/|man/|dash_query_builder/_imports_.py|dash_query_builder/.+\.(js))

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.3.5
      hooks:
          - id: ruff
            args: [--fix]
            exclude: dash_query_builder/DashQueryBuilder.py
          - id: ruff-format
            exclude: dash_query_builder/DashQueryBuilder.py
