# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
            exclude: ^(deps|inst/|R/|man/|dash_query_builder/_imports_.py)
          - id: check-yaml

    - repo: https://github.com/Zac-HD/shed
      rev: 2024.1.1
      hooks:
          - id: shed
            args: [--refactor, --py310-plus]
            types_or: [python, markdown, rst]

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.2.2
      hooks:
          - id: ruff
            exclude: dash_query_builder/DashQueryBuilder.py
