.dashQueryBuilder_js_metadata <- function() {
deps_metadata <- list(`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-mui-41b1562a.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-antd-1338e340.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-fluent-1d2adb03.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-mui-ba3c9f4a.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-fluent-0fc74c33.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-antd-aac516cf.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-mui-f92f78ac.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-mui-bootstrap.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-fluent-0bc0478e.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-mui-3fb7187e.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-antd-7d0ccfb8.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-antd-2f91e255.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-bootstrap-84459eac.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-antd-d6bcece5.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-antd-49d0a293.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-fluent-6aa332ca.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-fluent-b0f7b882.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-antd-19ba600e.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-bootstrap-5d3f7ed2.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-antd-e96e9bea.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-fluent-faf2d91f.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-fluent-1e04f4bb.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-mui-f46dc3dc.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-fluent-e96e9bea.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-fluent-36c4d91f.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-mui-58465378.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-antd-bcc0128f.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-fluent-bb06581e.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-antd-425383c7.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-fluent-ca7a69a6.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-mui-e96e9bea.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-mui-49d0a293.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-mui-0981405c.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-antd-b38587c7.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-bootstrap-e96e9bea.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/basic.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'proptypes.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_query_builder.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE), class = "html_dependency"))
return(deps_metadata)
}
