.dashQueryBuilder_js_metadata <- function() {
deps_metadata <- list(`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "0.2.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-material.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "0.2.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-mui.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "0.2.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-antd.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "0.2.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-bootstrap.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "0.2.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-basic.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "0.2.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-material.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "0.2.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-mui.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "0.2.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-antd.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "0.2.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-bootstrap.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "0.2.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-basic.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "0.2.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_query_builder.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "0.2.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_query_builder.shared.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "0.2.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_query_builder.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "0.2.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_query_builder.shared.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
