.dashQueryBuilder_js_metadata <- function() {
deps_metadata <- list(`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-mui-0dff58e9.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-fluent-e96e9bea.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-mui-d1e4702f.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-antd-6575d636.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-bootstrap-c4a691e0.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-antd-e4527a1e.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-fluent-4e83fca6.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-fluent-efef450f.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-fluent-2d48116b.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-antd-e139457f.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-mui-09ae1d44.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-fluent-62b537ca.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-antd-e96e9bea.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-bootstrap-e96e9bea.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-fluent-c8e5d056.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-mui-c7ba4e9c.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-mui-e84e36ce.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-fluent-b82ab764.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-fluent-f79ca946.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-mui-919d96d0.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-antd-d07461da.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-fluent-4fc3981f.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-antd-08125ffa.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-antd-6ef37c4b.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-antd-915e7c66.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-mui-e96e9bea.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-mui-1a84984e.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-mui-c30f4496.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-bootstrap-5d3f7ed2.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-mui-e47c2213.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/async-antd-6f0a41ad.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'js/basic.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_query_builder.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE), class = "html_dependency"),
`dash_query_builder` = structure(list(name = "dash_query_builder",
version = "1.0.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_query_builder.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashQueryBuilder",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
