name: Tests
on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
        types:
            - opened
            - synchronize

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.11'
            - uses: actions/cache@v4
              id: cache
              with:
                  path: ${{ env.pythonLocation }}
                  key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml', 'requirements-dev.txt')}}-test
            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: pip install -r requirements-dev.txt
            - name: Lint
              run: ruff dash_query_builder tests
            - name: Format
              run: ruff format dash_query_builder tests --check

    tests:
        runs-on: ubuntu-latest
        needs: lint
        strategy:
            matrix:
                python-version: [3.8, 3.9, '3.10', '3.11', '3.12']
        steps:
            - uses: actions/checkout@v4
            - name: setup python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install chrome
              uses: nanasess/setup-chromedriver@v2
            - run: |
                  export DISPLAY=:99
                  chromedriver --url-base=/wd/hub &
                  sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
            - uses: actions/cache@v4
              id: cache
              with:
                  path: ${{ env.pythonLocation }}
                  key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml', 'requirements-dev.txt') }}-test
            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: pip install -r requirements-dev.txt
            - name: Test
              run: pytest
